- name: Configure icap-server
  hosts: icap-server
  become: yes
  tasks:
  - name: Enable claimAv daemon
    ansible.builtin.service:
      name: clamav-daemon
      enabled: yes
      state: started
  - name: Enable and start icap-service
    ansible.builtin.service:
      name: c-icap
      enabled: yes
      state: started
  - name: Configure C-ICAP to use ClamAV
    lineinfile:
      path: /usr/local/etc/c-icap.conf
      line: 'Include virus_scan.conf'
      state: present
  - name: Enable clamd_mod
    ansible.builtin.lineinfile:
      path: /usr/local/etc/c-icap.conf
      line: Include clamd_mod.conf
      state: present
    notify: Restart C-ICAP
  handlers:
  - name: Restart C-ICAP
    ansible.builtin.service:
      name: c-icap
      state: restarted
      enabled: yes
